version: "3.7"
services:
  app:
    user: node
    build:
      target: dev
      context: .
      args:
        USERUID: 1000
    container_name: animal-manager-app
    working_dir: /app
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/app
    depends_on:
      - db
  db:
    image: "postgres:11-alpine"
    container_name: animal-manager-db
    volumes:
      - animal-manager-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medondo
volumes:
  animal-manager-db-data:
    driver: local
